"""
Feature extraction for LFW images.
Resizes each image to image_size x image_size grayscale, flattens, and L2-normalizes.
Record IDs match the format used in make_pairs.py: lfw_record_{label}_{i:06d}
"""

import numpy as np
import os


def _resize_grayscale(image: np.ndarray, size: int) -> np.ndarray:
    """Resize (H, W, 3) uint8 image to (size, size) grayscale using nearest-neighbor."""
    gray = image.mean(axis=2)  # (H, W)
    h, w = gray.shape
    row_idx = (np.arange(size) * h / size).astype(int)
    col_idx = (np.arange(size) * w / size).astype(int)
    return gray[np.ix_(row_idx, col_idx)]


def extract_feature(image: np.ndarray, image_size: int = 32) -> np.ndarray:
    """
    Extract an L2-normalized feature vector from a single LFW image (H x W x 3 uint8).
    Returns a float32 vector of length image_size * image_size.
    """
    resized = _resize_grayscale(image, image_size)
    vec = resized.astype(np.float32).flatten()
    norm = np.linalg.norm(vec)
    if norm > 1e-10:
        vec = vec / norm
    return vec


def build_feature_map(config: dict) -> dict:
    """
    Load all LFW images via TFDS and extract features.
    Returns dict: record_id -> L2-normalized feature vector.
    Record IDs are deterministic and match those generated by make_pairs.py.
    """
    import tensorflow_datasets as tfds

    cache_dir = config["data"]["cache_dir"]
    image_size = config["features"]["image_size"]

    print(f"[features] Loading LFW images from TFDS cache ({cache_dir}) ...")
    ds = tfds.load(
        config["data"]["tfds_name"],
        split="train",
        data_dir=cache_dir,
        shuffle_files=False,
    )

    features = {}
    for i, record in enumerate(tfds.as_numpy(ds)):
        label = (
            record["label"].decode("utf-8")
            if isinstance(record["label"], bytes)
            else str(record["label"])
        )
        record_id = f"lfw_record_{label}_{i:06d}"
        features[record_id] = extract_feature(record["image"], image_size)
        if (i + 1) % 2000 == 0:
            print(f"  processed {i + 1} images ...")

    print(f"[features] Extracted features for {len(features)} images.")
    return features


def save_features(features: dict, output_path: str):
    """Save feature map to a compressed .npz file."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    record_ids = list(features.keys())
    vectors = np.stack([features[r] for r in record_ids])
    np.savez_compressed(output_path, record_ids=np.array(record_ids), vectors=vectors)
    print(f"[features] Saved {len(record_ids)} feature vectors to {output_path}")


def load_features(output_path: str) -> dict:
    """Load feature map from a .npz file."""
    data = np.load(output_path, allow_pickle=True)
    record_ids = data["record_ids"]
    vectors = data["vectors"]
    return {rid: vectors[i] for i, rid in enumerate(record_ids)}
